CREATE DATABASE practiceday22;
USE practiceday22;

-- ============================================
-- TABLE 1: EMPLOYEES
-- ============================================

CREATE TABLE employees (
    emp_id INT PRIMARY KEY,
    emp_name VARCHAR(50),
    department VARCHAR(50),
    salary DECIMAL(10,2),
    manager_id INT NULL,
    hire_date DATE
);

INSERT INTO employees
(emp_id, emp_name, department, salary, manager_id, hire_date)
VALUES
(101, 'Amit',   'IT',    75000, 105, '2021-01-15'),
(102, 'Neha',   'HR',    60000, 106, '2022-03-10'),
(103, 'Rahul',  'IT',    90000, 105, '2020-07-20'),
(104, 'Priya',  'Sales', 65000, 107, '2021-11-05'),
(105, 'Vikram', 'IT',   120000, NULL, '2018-05-12'),
(106, 'Sneha',  'HR',    95000, NULL, '2019-08-18'),
(107, 'Karan',  'Sales',110000, NULL, '2017-02-25'),
(108, 'Riya',   'IT',    85000, 105, '2023-01-09'),
(109, 'Arjun',  'Sales', 70000, 107, '2022-06-14'),
(110, 'Pooja',  'HR',    72000, 106, '2024-02-01');


-- ============================================
-- TABLE 2: SALES
-- ============================================

CREATE TABLE sales (
    sale_id INT PRIMARY KEY,
    emp_id INT,
    sale_date DATE,
    amount DECIMAL(10,2),

    FOREIGN KEY (emp_id)
        REFERENCES employees(emp_id)
);

INSERT INTO sales
(sale_id, emp_id, sale_date, amount)
VALUES
(1,  101, '2025-01-10',  50000),
(2,  101, '2025-02-15',  70000),
(3,  103, '2025-01-20', 120000),
(4,  103, '2025-03-05',  90000),
(5,  104, '2025-01-25',  60000),
(6,  108, '2025-02-10',  80000),
(7,  109, '2025-01-18',  55000),
(8,  109, '2025-03-22',  75000),
(9,  110, '2025-02-12',  40000),
(10, 102, '2025-03-15',  65000);


-- Q1. Find employees whose salary is greater than the average salary
-- of all employees.
-- Display employee name, department and salary.

select emp_name, department, salary from employees where salary > (select avg(salary) from employees);


-- Q2. Find employees who earn the highest salary in their department.
-- Display employee name, department and salary.
-- Do NOT use window functions.

select emp_name, department, salary from employees e1 
where salary = (select max(salary) 	from employees e2 where 
e2.department = e1.department);

-- Q3. Find employees whose salary is greater than the average salary
-- of their respective department.
-- Display employee name, department and salary.
-- Hint: The average salary must be calculated separately for each employee's department.

select emp_name, department, salary from employees e1 
where salary > (select avg(salary) from employees e2 where 
e2.department = e1.department);


-- Q4. Find the employee(s) who have generated the highest total sales.
-- Display employee name and total sales.
-- Use a subquery to compare each employee's total sales with the maximum
-- total sales generated by any employee.

select e.emp_name, sum(s.amount) as total_sales from employees e left join sales s on
e.emp_id = s.emp_id group by e.emp_id, e.emp_name HAVING SUM(s.amount) = (
    SELECT MAX(emp_total.total_sales)
    FROM (
        SELECT SUM(amount) AS total_sales
        FROM sales
        GROUP BY emp_id
    ) AS emp_total
);


-- Q5. Find employees who have made at least one sale greater than
-- the average sale amount of ALL sales.
-- Display employee name and sale amount.
-- Use EXISTS or a correlated subquery.

SELECT emp_name
FROM employees e
WHERE EXISTS (
    SELECT 1
    FROM sales s
    WHERE s.emp_id = e.emp_id
      AND s.amount > 100000
);




-- Q6. Find employees whose salary is greater than their manager's salary.
-- Display employee name, employee salary, manager name and manager salary.
-- Solve this using a correlated subquery rather than a normal JOIN.


SELECT 
    e.emp_name AS employee_name,
    e.salary AS employee_salary,
    (
        SELECT m.emp_name
        FROM employees m
        WHERE m.emp_id = e.manager_id
    ) AS manager_name,
    (
        SELECT m.salary
        FROM employees m
        WHERE m.emp_id = e.manager_id
    ) AS manager_salary
FROM employees e
WHERE e.salary > (
    SELECT m.salary
    FROM employees m
    WHERE m.emp_id = e.manager_id
);

-- Q7. Find employees who have NOT generated any sales.
-- Display employee name and department.
-- Solve using NOT EXISTS.

SELECT 
    e.emp_name, e.department
FROM
    employees e
WHERE
    NOT EXISTS( SELECT 
            1
        FROM
            sales s
        WHERE
            s.emp_id = e.emp_id);

-- Q8. Find the highest-paid employee(s) in each department
-- whose salary is also greater than the company's overall average salary.
-- Display employee name, department and salary.

SELECT 
    e1.emp_name,
    e1.department,
    e1.salary
FROM employees e1
WHERE e1.salary = (
    SELECT MAX(e2.salary)
    FROM employees e2
    WHERE e2.department = e1.department
)
AND e1.salary > (
    SELECT AVG(e3.salary)
    FROM employees e3
);

-- Q9. Find employees whose total sales are greater than the average
-- total sales of all employees who have made at least one sale.
-- Display employee name and total sales.
-- This requires comparing each employee's aggregated sales against
-- an aggregated value calculated from other employees.

SELECT 
    e.emp_name,
    (
        SELECT SUM(s.amount)
        FROM sales s
        WHERE s.emp_id = e.emp_id
    ) AS total_sales
FROM employees e
WHERE (
    SELECT SUM(s.amount)
    FROM sales s
    WHERE s.emp_id = e.emp_id
) > (
    SELECT AVG(employee_total)
    FROM (
        SELECT 
            s2.emp_id,
            SUM(s2.amount) AS employee_total
        FROM sales s2
        GROUP BY s2.emp_id
    ) AS totals
);

-- Q10. Find employees who have made a sale in every month in which
-- at least one sale occurred.
-- Display employee name.
-- Use a correlated subquery / NOT EXISTS approach.
-- This is an interview-level relational division problem.

SELECT e.emp_name
FROM employees e
WHERE NOT EXISTS (
    SELECT 1
    FROM (
        SELECT DISTINCT MONTH(s.sale_date) AS sale_month
        FROM sales s
    ) m
    WHERE NOT EXISTS (
        SELECT 1
        FROM sales s2
        WHERE s2.emp_id = e.emp_id
          AND MONTH(s2.sale_date) = m.sale_month
    )
);
